### PR TITLE
Set pill background color when the user is mentioned

### PR DESCRIPTION
**Pull request by yostyle**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [x] Other :

## Motivation and context

#1075 

## Screenshots / GIFs

|Before|After|
|-|-|
|image|image|

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/tchapgouv/tchap-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/tchapgouv/tchap-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/tchapgouv/tchap-android/blob/develop/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt)

### CODE REVIEW

**Review by NicolasBuquet — APPROVED** [review]
Ok, mais ne faudrait-il pas aussi traiter la pill présente dans une citation (celle en rouge dans les captures) ?

**Comment by yostyle** [comment]
> Ok, mais ne faudrait-il pas aussi traiter la pill présente dans une citation (celle en rouge dans les captures) ?

c'est une image iOS dans la capture android

**Comment by areox-net** [comment]
Merci @yostyle , 
as tu aussi pris en compte la dernière ligne du PDF, quand on repond à l'user sans le mentionner dans le texte. Dans ce cas on colore le text en bleu et on augmente la graisse ?

Screenshot 2024-06-26 at 09 39 58

**Comment by areox-net** [comment]
@yostyle Tu peux ignorer mon commentaire précedent. La pastille bleue suffit ur mobile.

**Pull request merged**
